### ISSUE TITLE
Register package?

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Polymake.jl#102]
I think we should officially register the package such that it can be installed via 
```julia
pkg> add Polymake
```

Also to introduce some versioning would make it easier to coordinate breaking changes.

**Comment by kalmarek** [comment]
I'm for it

**Comment by saschatimme** [comment]
Just discussed this with @benlorenz and we want to wait for the next polymake release (next week)

**Comment by sebasguts** [comment]
I am currently not a fan of this, because

1. We do not have docu yet, which is very bad
2. Mac installation is complicated, Windows is not possible

While the second one is a minor issue, the first one is a major. I would not like to register the package without suitable documentation. Because currently it is in development, which means no docs are fine. But once it is registered, it is kind of released, and then no docs are not acceptable, as it draws bad light on the project, and people will complain and maybe even abandon it.

But, out of interest, what would registering imply:
* How do we make releases and updates?
* How long does it take for the updates to be picked up?
* Can this process be pipelined for every merged commit, or do we have to do manual work?

**Comment by saschatimme** [comment]
* How do we make releases and updates?
The most convenient thing is to use [Attobot](https://github.com/attobot/attobot). We just have to create a new release in the Github UI and Attobot automatically creates a PR to the [METADATA.jl](https://github.com/JuliaLang/METADATA.jl) repository.

* How long does it take for the updates to be picked up?
For regiestering a package, they usually keep a PR open 3 days until it is merged. Package updates are currently processed automatically and availablel ca. 30 minutes after a release is tagged.
* Can this process be pipelined for every merged commit, or do we have to do manual work?
Well, we just have to add a new release.
