### ISSUE TITLE
Sparse system tests flaky

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Polymake.jl#196]
This test 

https://github.com/oscar-system/Polymake.jl/blob/ca21f7e85f772b9fecd7ac3aacefb44ebc93cfd0/test/sparsematrix.jl#L392-L400

is quite flaky on CI which seems ... odd.

**Comment by kalmarek** [comment]
it might have to do with floating point zeros (sme subnormals are treated as zeros?)
@alexej-jordan 
in the worst case we can add `Random.seed!(1)`, but that only masks the issue which should be better solved

**Comment by saschatimme** [comment]
yeah let's put a seed at the beginning front for now...

Also why do we have such a big test matrix?

**Comment by kalmarek** [comment]
I'd prefer a real solution though; The size is @alexej-jordan s invention; it allocates a quarter of million entries, which seems a little bit excessive; especially that my next aim is at speeding-up tests

**Comment by saschatimme** [comment]
Sure, I will leave #197 in case we want to have a (temporarily) quick fix.
@alexej-jordan a matrix even with only 1% non-zero entries is quite often not considered sparse enough to justify sparse matrix storage format

**Comment by alexej-jordan** [comment]
I'm on it, will now try to reproduce. do we have any additional information from CI why this test fails? @saschatimme 
additionally to the idea @kalmarek mentioned i could also think of some problem when sorting the entries, but i thought this should work out due to the way the entries are sorted within their corresponding sparse matrix structure.
actually, the big size of the test matrix is a relic of trying to figure this out; i wanted a good chance that some rows and/or columns contain several entries

**Comment by alexej-jordan** [comment]
after some more testing, @kalmarek seems to have called the problem by its name: subnormal numbers.
```
julia> eps(Float32)
1.1920929f-7
```

and every time i could reproduce the failure it was caused by the only entry in `jsm` which was below the mentioned epsilon, resulting in the corresponding entry of `psm` being zero.
setting the same value within a dense `Polymake.Matrix{Float64}` works perfectly fine which leads me to assume that the internal `iszero` method of polymake might use this epsilon, or maybe somewhere in the process of setting the entry.
of course, we could quickly make the tests work by forcing Float32 values for the random sparse matrix, but it would be better if we fully support Float64 in `Polymake.SparseMatrix` the same as in `Polymake.Matrix`

**Comment by benlorenz** [comment]
The exact value is slightly different `1.0e-7`, see `lib/core/src/inlines.cc`.

This can be read from the following static variable:
```c++
pm::object_traits<double>::global_epsilon;
```
There should a function which reads this from the Julia side so we can adjust the julia matrix accordingly in the tests.

Furthermore, there is a class `pm::local_epsilon_keeper` which can be used to adjust the value at runtime by calling the constructor with a double. The value will stay different as long as this object stays alive (I haven't tested this but it should work that way):
```c++
// here we use the default epsilon
SparseMatrix<double> s(something);
{
   // new epsilon
   pm::local_epsilon_keeper eps(1e-10);
   SparseMatrix<double> s2(something);
   // compute some stuff
}
// reverts to the original epsilon here
```

If the `local_epsilon_keeper` is made available as a type for julia one could control this value easily from the julia side.

**Comment by saschatimme** [comment]
In Julia `findnz` only computes *structural* non-zeros. So basically the number of elements stored.

```
julia> A = sparse([1,2], [3,4], [2, 1e-100])
2×4 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 3]  =  2.0
  [2, 4]  =  1.0e-100

julia> findnz(A)
([1, 2], [3, 4], [2.0, 1.0e-100])

help?> findnz
search: findnz findnext findmin! findmin

  findnz(A)

  Return a tuple (I, J, V) where I and J are the row and column indices of the stored ("structurally non-zero") values in sparse matrix A, and V is
  a vector of the values.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> A = sparse([1 2 0; 0 0 3; 0 4 0])
  3×3 SparseMatrixCSC{Int64,Int64} with 4 stored entries:
    [1, 1]  =  1
    [1, 2]  =  2
    [3, 2]  =  4
    [2, 3]  =  3
  
  julia> findnz(A)
  ([1, 1, 3, 2], [1, 2, 2, 3], [1, 2, 4, 3])
```

I am a little bit puzzled by the polymake implementation. Can we just set the `global_epsilon` to 0?

**Comment by benlorenz** [comment]
Our floating point matrices are not that much for data storage but for computations where a reasonable zero check is important (1e-7 might be rather large for this but we need these coordinates mostly for visualization so this is not really critical).

Setting it to 0 can cause infinite loops or other problems. A first try of the polymake testsuite with this set to 0 ends with `Segmentation fault` and there were some other failed test as well.

We discussed with @alexej-jordan today that he will remove entries smaller than the polymake epsilon before passing the matrix to polymake so `findnz` can be tested properly with the same matrix.

**Comment by kalmarek** [comment]
`Segmentation fault` sounds more like a improper handling of the epsilon, than a feature ;)
