### ISSUE TITLE
Drop CxxWrap 0.9 support and simplify code again?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Polymake.jl#262]
Right now the `master` branch "supports" both CxxWrap 0.9 an 0.10, and has to jump through some hoops to do so. But what is the benefit of this? I can't think of any -- sure, it means that at least in theory, Polymake.jl can be used in parallel with "old" Singular.jl -- but I'd rather just update both simultaneously to CxxWrap 0.10.1 and be done with it. See also https://github.com/oscar-system/Singular.jl/pull/213

Am I missing something?

CC: @fieker

**Comment by fingolfin** [comment]
I am seeing random crashes which seem to be related to CxxWrap 0.9.1 on several systems (e.g. all Travis jobs for Singular.jl currently experience them) which go away with CxxWrap 0.10.1. Singular is (from my POV) ready to switch to 0.10.1 (again, see https://github.com/oscar-system/Singular.jl/pull/213)

I think we ought to coordinate release of the Polymake.jl 0.4.0 resp. Singular.jl 0.3.0 ; but I think before that, this issue should be resolved.

@benlorenz @saschatimme @kalmarek @micjoswig am I missing something? What is the benefit for having CxxWrap 0.9 in the list?

**Comment by kalmarek** [comment]
which parts of the code will be actually simplified if we drop 0.9?
If Singular drops 0.9 why is it necessary to also drop 0.9 here? 

I might misrepresent stuff in my memory but in the course of allowing 0.10 we added `CxxWrap` version checking (we want to keep it), and then there was just one tiny (2-) change in `deps/src/polymake_rationals.cpp`. Were there any hoops elsewhere?

**Comment by fingolfin** [comment]
Simplification: You can again remove the code which makes the simultaneous support for CxxWrap 0.9 and 0.10 at least bearable (which changes "will cause crashes for some users" to "will force some users to manually rebuild Polymake.jl"). Also: removes the situations where users will have to manually rebuild Polymake.jl (well, or at least reduce them, as any kind of temporary build failure also forces the user to do that, until Julia becomes more powerful). 

We need to coordinate releases of Polymake.jl and Singular.jl only in the sense that this is a corrollary of coordinating with Oscar.jl: If I release a Singular.jl version which only supports CxxWrap 0.10, then I can't update Oscar.jl to use that before there's also a Polymake.jl release with CxxWrap 0.10 support.

And I want to release a Singular.jl version which only uses CxxWrap 0.10 because there are crashes with 0.9 and Julia 1.4 (!) that go away with CxxWrap 0.10, see https://travis-ci.com/github/oscar-system/Singular.jl/jobs/320533816. Of course if somebody knows a way to resolve that with 0.9, that's also nice; I don't care about 0.9 vs. 0.10 as such; but i see that one fixes an issue, and I'd rather not spend time to figure out a way to make it also work with the older version.

Finally, I don't want to support 0.9 *and* 0.10 simultaneously in Singular.jl because that's simply a waste of time for a fringe "benefit" (in fact so far nobody has even attempted to explain to me what the benefit of such a support is... So I'll repeat the question again: what's the motivation for supporting 0.9 *and* 0.10, anyway? All it seems to do is cause extra work, requires extra testing, adds new failure modes -- for what?

**Comment by kalmarek** [comment]
the only workaround I'm aware of was with `prefix_path` and has been already removed:
https://github.com/oscar-system/Polymake.jl/commit/c59d4bce9f5cb5ddab77ccce527d94ad175e1cd8
when we required `0.9.1` or `0.10.1`; 
>Also: removes the situations where users will have to manually rebuild Polymake.jl

yes, I agree; but unless your issue is not about smooth `Polymake.jl` releases, but about smooth `Oscar.jl` releases, requiring it there is the solution

> Finally, I don't want to support 0.9 and 0.10 simultaneously in Singular.jl because that's simply a waste of time for a fringe "benefit"

I see no reason why would You need to support both in `Singular.jl`? since `Polymake.jl` supports `0.10`, just drop `0.9` in `Singular.jl` and bump versions in `Oscar.jl`. Or maybe I don't understand the problem?

matrix testing is free and increases our chances of spotting potential bugs ;)

**Comment by fingolfin** [comment]
It seems that if I say too many things, everything is addressed but my central question:

What are the benefits to you to supporting CxxWrap 0.9 in Polymake.jl?

**Comment by kalmarek** [comment]
I see none tangible, but I also don't see costs to do so

**Comment by fingolfin** [comment]
@kalmarek so, you have no reason, good.

On the other hand, the OSCAR PIs agreed that we want to standardize all Oscar subpackages on a single CxxWrap major version (see also https://github.com/oscar-system/Oscar.jl/issues/80). This used to be 0.9, now it is 0.10.

So my viewpoint is that Polymake.jl should drop 0.9 support and then make a release. If Polymake.jl developers still disagree: I will not keep wasting time by arguing for this further, I'll leave it to @micjoswig to then adjust https://github.com/oscar-system/Oscar.jl/issues/80 to then reflect this.

**Comment by micjoswig** [comment]
Well, it is important to have an explicit list of versions that OSCAR supports, e.g., CxxWrap 0.10.1.  

I do not see much of a reason why some component (e.g., Polymake.jl) cannot support additional versions.  I think this will happen all the time (not only with Polymake.jl but also with other Julia components outside the OSCAR core, e.g., for visualization).

If you should fear complicated code forks (because someone might rely on Polymake.jl and CxxWrap 0.9; whoever that may be, other than ourselves) we could add a deprecation message for CxxWrap 0.9 in Polymake.jl.

Does that get rid of your headaches?

On 21.04.20 16:55, Max Horn wrote:
> @kalmarek so, you have no reason, good.
> 
> On the other hand, the OSCAR PIs agreed that we want to standardize all Oscar subpackages on a single CxxWrap major version (see also https://github.com/oscar-system/Oscar.jl/issues/80). This used to be 0.9, now it is 0.10.
> 
> So my viewpoint is that Polymake.jl should drop 0.9 support and then make a release. If Polymake.jl developers still disagree: I will not keep wasting time by arguing for this further, I'll leave it to @micjoswig to then adjust https://github.com/oscar-system/Oscar.jl/issues/80 to then reflect this.
> 
> 

-- 
Prof. Dr. Michael Joswig           <joswig@math.tu-berlin.de>
Technische Universitaet      Institut fuer Mathematik, MA 6-2
Str. des 17. Juni 136                 D-10623 Berlin, Germany
phone +49 (30) 314-75904               fax +49 (30) 314-25047

**Comment by fingolfin** [comment]
CxxWrap is different from other components, in that it is one of the few things that forces us to compile code on the user's machine; which is error prone, and can easily lead to segfaults if no attention is paid.

As Marek stated, there is no reason for Polymake.jl to support it, other than "we can".

Showing a deprecation message makes no sense to me: my goal is to (a) avoid potential problems for users, and (b) reduce the work we have to put in. Implementing a deprecation message doesn't help with (a) and is strictly more work than just changing the "compat" entry from "0.9,0.10" to "0.10", so it doesn't help with (b) either.

That said, I don't think it makes sense to continue to debate this. I'll close this issue, and instead open a new one requesting a release of Polymake.jl, so we can go on.
