### ISSUE TITLE
Make a release with CxxWrap 0.10 support

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Polymake.jl#264]
Please make a release with CxxWrap 0.10 support. Then once Singular.jl does the same (hopefully very soon) we can also make a release of Oscar.jl using those new versions.

**Comment by kalmarek** [comment]
I will write release notes tonight but not everything is done yet (we have signal handler problems with polymake right now + other small fixes) and send an email announcing everything to the Oscar-dev list as soon as we are ready (hopefully this week).

If You insist on making it fast, we can shorten the time between the announcement and tagging to 7 days (from 14 as in the previous announcement). I would greatly appreciate if other projects could send such announcements as well, so that everybody in the team can have a rough picture what's going on without sifting through git history, but oh well... ;)

**Comment by fingolfin** [comment]
Thank you. I understand and agree.
