### ISSUE TITLE
visualize_in_surface not in JSON

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Polymake.jl#95]
There is the user function [`visualize_in_surface`](https://polymake.org/release_docs/snapshot/tropical.html#tropical__visualize_in_surface__97) in the application `tropical`.
But this is not listed in the auto generated JSON and thus also not available right now.

Any idea why we miss that? @sebasguts @benlorenz

**Comment by sebasguts** [comment]
@saschatimme I guess because of argument conversion limitations, it was not generated.

With #94 , it is generated.

**Comment by benlorenz** [comment]
On the current master I also have this function in `tropical.json` and `tropical.jl`.

But our argument list (one mandatory argument) is not quite correct as the polymake function accepts `Cycle<Addition>, @`, i.e. one Cycle plus arbitrary further arguments, I will have a look at this since the json also doesn't have any info for the remaining arguments.

Did you configure your polymake with --without-atint?

**Comment by saschatimme** [comment]
@sebasguts  Ah good to know, sorry that I didn't test this. I didn't want to update until my presentation is over ;D

**Comment by saschatimme** [comment]
No I have atint. But I (or more Lars for me) needed to fix something on polymake master to get things working. In particular the second argument shouldn't be a perl array, but rather an array of big objects (cycles).
